%YAML:1.0
---
Camera:
  # KITTI Intrinsics from kitti_intrinsics.yaml
  K: !!opencv-matrix
    rows: 3
    cols: 3
    dt: d
    data: [ 7.215377e+02, 0.000000e+00, 6.095593e+02, 
            0.000000e+00, 7.215377e+02, 1.728540e+02, 
            0.000000e+00, 0.000000e+00, 1.000000e+00 ]
  D: !!opencv-matrix
    rows: 1
    cols: 5
    dt: d
    data: [ 0.0, 0.0, 0.0, 0.0, 0.0 ]
  Model: "plumb_bob"

Transforms:
  # Robot to Camera Transform (KITTI Setup)
  # X_cam = -Y_rob, Y_cam = -Z_rob + 1.65, Z_cam = X_rob
  T_robot_cam: !!opencv-matrix
     rows: 4
     cols: 4
     dt: d
     data: [ 0,  0,  1, 0,
            -1,  0,  0, 0,
             0, -1,  0, 1.65,
             0,  0,  0, 1 ]

  # Robot to Virtual Ortho View
  # Looking Down from Z=10m, centered at X=10m.
  # X_v = Y_r, Y_v = -X_r + 10, Z_v = -Z_r + 10
  # Matrix mapping Robot Point -> Virtual Frame Point
  T_robot_virtual: !!opencv-matrix
     rows: 4
     cols: 4
     dt: d
     data: [  0,  1,  0, 60,
             -1,  0,  0, -25,
              0,  0, -1, 0.001,
              0,  0,  0, 1 ]

Input:
  source: "image"
  image_path: "data/kitti_sample.png"

TargetSpec:
  meter_per_px: 0.2
  width: 500
  height: 500
